---
# SentinelCam CamWatcher-only Deployment Playbook
# Use this when you only want to deploy camwatcher

- name: Deploy CamWatcher to data sinks
  hosts: datasinks
  become: yes
  roles:
    - sentinelcam_base    # Common base configuration
    - camwatcher
