---
# SentinelCam Watchtower Role - Handlers
# Note: Service restart handler provided by sentinelcam_base role

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart lightdm
  become: yes
  ansible.builtin.systemd:
    name: lightdm
    state: restarted
