# Node-specific configuration for lab1 outpost
---
# ImageNode configuration using unified template
imagenode_config:
  node_name: outpost
  cameras:
    P1:                          # PiCamera
      viewname: PiCamera
      resolution: (640, 480)
      framerate: 32
      vflip: false
      detector:
        ROI: (10,20),(70,80)
        detectobjects: mobilenetssd
        accelerator: none
        sentinel_tasks:
          person: GetFaces2

imagenode_venv_path: "{{ sentinelcam_venv_py3cv4 }}"
